baseURL = "http://coqu.io/"
languageCode = "en-us"
title = "Kevin Ballard"
author = "Kevin Ballard"

theme = "arabica"
paginate = 10

[params]
custom_css = ["css/custom.css"]

[markup]
[markup.highlight]
style = "monokailight"

[deployment]

[[deployment.targets]]
name = "S3"
URL = "s3://coqu.io?region=ca-central-1"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
